zuul:
  prefix: /api
  routes:
    user:
      path: /cat/**
      serviceId: CAT

    country:
      path: /country/**
      serviceId: COUNTRY

    about:
      path: /about/**
      servcieId: ABOUT

    chat:
      path:/chat/**
      serviceId: ECHATS

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 30000

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 41000
